version: "3"
services:
  api:
    build: .
    command: sh -c "npm install && npm run start:dev"
    volumes:
      - .:/api
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:12-alpine
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=mypuppies
      - POSTGRES_PASSWORD=mypuppies
      - POSTGRES_DB=mypuppies
